selenium-hub:
  image: selenium/hub
  ports:
  - 4444:4444
  environment:
  - GRID_MAX_SESSION=30

chrome:
  image: selenium/node-chrome
  environment:
  - NODE_MAX_INSTANCES=30
  - NODE_MAX_SESSION=30
  links:
  - selenium-hub:hub
  volumes:
  - /dev/shm:/dev/shm # Mitigates the Chromium issue described at https://code.google.com/p/chromium/issues/detail?id=519952
